### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by syon321** [phuongvnc/CPMenuView#12]
In  CPMenuView.swift class (xcode 8.3).
 
 private func getTheta() -> Double ...
let numberItem: Double = Double(datasource!.menuViewNumberOfItems() == 0 ? 1 : datasource!.menuViewNumberOfItems() - 1)

fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by phuongvnc** [comment]
Please conform datasource of MenuView.

**Comment by syon321** [comment]
Thank you
