### ISSUE TITLE
Wrong syntax to install this POD: "pod "CPMenuView" ~> '1.0.1'"

### ISSUE THREAD

**Issue by GotiMehta** [phuongvnc/CPMenuView#5]
Hey,

When I tried to install this pod using  `pod "CPMenuView" ~> '1.0.1'`, it gives the below `error:Invalid `Podfile` file: syntax error, unexpected '~', expecting keyword_end
pod "CPMenuView" ~> '1.0.1'
                  ^.`
So I replaced that line with   **pod "CPMenuView",'~> 1.0.1'**  and the error was resolved. 
I just posted this solution if anybody faces the same.

**Comment by phuongvnc** [comment]
I already fix it in #6. Thanks
