### ISSUE TITLE
UPPER/LOWER HALF

### ISSUE THREAD

**Issue by Marlunes** [phuongvnc/CPMenuView#8]
Is it possible to have an upper/lower half feature? Currently this on only have left side and right side half.

**Comment by phuongvnc** [comment]
OK, i will add upper and lower half for it.Please waiting it

**Comment by MarcAMartin** [comment]
Still looking for the upper and lower, it doesn't seem to be included in 1.0.2

**Comment by Marlunes** [comment]
you can download the example and copy the classes instead. it should word

**Comment by MarcAMartin** [comment]
@Marlunes Yup, that worked. Reminds me of the pre-cocoa days!

**Comment by phuongvnc** [comment]
I already update cocoapods. You could use cocoapods with version 1.1.0
